# This is a basic workflow to help you get started with Actions

name: myBlog_deploy

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

     # 使用的node版本   
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@main
        with:
          node-version:  ${{ matrix.node }}
		# 执行安装
      - name: Install dependencies
        run: npm install
    # 执行打包
      - name: Build Page
        run: npm run build
    # 执行部署
      - name: Deploy to Pages
        run: |
          cd .vitepress/dist 
          git init
          git config user.name "ChrisLee0211"
          git config user.email "${{ secrets.GIT_EMAIL }}"
          git add -A
          git commit -m 'deploy'
          git push -f https://ChrisLee0211:${{ secrets.ACCESS_TOKEN }}@github.com/ChrisLee0211/myBlog.git master:gh-pages
          cd -
    
